figaro_syllable_lines = [
    [],
    [],
    [],
    [
        ["DH", "AH"],
        "",
        ["R", "EH", "S", "T"],
        "",
        ["IH", "Z"],
        "",
        ["EH", "M", "P"],
        ["T", "IY"],
        "",
        ["W", "IH", "DH"],
        "",
        ["N", "OW"],
        "",
        ["B", "R", "EY", "N"],
        "",
        ["B", "AH", "T"],
        "",
        ["DH", "AH"],
        "",
        ["K", "L", "EH"],
        ["V", "ER"],
        "",
        ["N", "ER", "D"],
    ],
    [
        ["DH", "AH"],
        "",
        ["B", "EH", "S", "T"],
        "",
        ["EH", "M"],
        ["S", "IY"],
        "",
        ["W", "IH", "DH"],
        "",
        ["N", "OW"],
        "",
        ["CH", "EY", "N"],
        "",
        ["Y", "AA"],
        "",
        ["EH"],
        ["V", "ER"],
        "",
        ["HH", "ER", "D"],
    ],
    [
        ["T", "EY", "K"],
        "",
        ["IH", "T"],
        "",
        ["F", "R", "AH", "M"],
        "",
        ["DH", "AH"],
        "",
        ["T", "EH", "K"],
        "",
        ["N", "AY", "N"],
        "",
        ["HH", "OW", "L"],
        ["D", "ER"],
    ],
    [
        ["DH", "EY", "V"],
        "",
        ["B", "IH", "T"],
        "",
        ["B", "AH", "T"],
        "",
        ["D", "OW", "N", "T"],
        "",
        ["N", "OW"],
        "",
        ["DH", "EH", "R"],
        "",
        ["N", "EH", "K"],
        "",
        ["SH", "AY", "N"],
        "",
        ["F", "R", "AH", "M"],
        "",
        ["SH", "IH"],
        ["N", "OW"],
        ["L", "AH"],
    ],
    [
        ["EH"],
        ["V", "R", "IY"],
        ["TH", "IH", "NG"],
        "",
        ["DH", "AE", "T"],
        "",
        ["G", "L", "IH"],
        ["T", "ER", "Z"],
        "",
        ["EY", "N", "T"],
        "",
        ["F", "IH", "SH"],
        ["S", "K", "EY", "L"],
    ],
    [
        ["L", "EH"],
        ["M", "AH"],
        "",
        ["TH", "IH", "NG", "K"],
        "",
        ["D", "OW", "N", "T"],
        "",
        ["L", "EH", "T"],
        "",
        ["HH", "ER"],
        "",
        ["F", "EY", "N", "T"],
        "",
        ["G", "EH", "T"],
        "",
        ["IH"],
        ["SH", "M", "IY", "L"],
    ],
    [
        ["AH"],
        "",
        ["SH", "AA", "T"],
        "",
        ["AH", "V"],
        "",
        ["JH", "AE", "K"],
        "",
        ["G", "AA", "T"],
        "",
        ["HH", "ER"],
        "",
        ["B", "AE", "K"],
        "",
        ["IH", "T", "S"],
        "",
        ["N", "AA", "T"],
        "",
        ["AE", "N"],
        "",
        ["AE", "K", "T"],
        "",
        ["S", "T", "AE", "K"],
    ],
    [
        ["F", "ER"],
        ["G", "AA", "T"],
        "",
        ["AH"],
        ["B", "AW", "T"],
        "",
        ["DH", "AH"],
        "",
        ["K", "AE"],
        ["K", "AH"],
        ["L", "AE", "K"],
        "",
        ["HH", "AA"],
        ["L", "AH"],
        "",
        ["B", "AE", "K"],
        "",
        ["K", "L", "AE", "K"],
        "",
        ["K", "L", "AE", "K"],
        "",
        ["B", "L", "AA"],
        ["K", "AH"],
    ],
    [
        ["V", "IH"],
        ["L", "AH"],
        ["N", "IY"],
        "",
        ["F", "IY", "L"],
        "",
        ["HH", "IH", "M"],
        "",
        ["IH", "N"],
        "",
        ["Y", "AA"],
        "",
        ["HH", "AA", "R", "T"],
        "",
        ["CH", "AE"],
        ["K", "R", "AH"],
        "",
        ["CH", "AA", "R", "T"],
        "",
        ["T", "AA"],
        ["P", "AH"],
    ],
    [
        ["S", "T", "AA", "R", "T"],
        "",
        ["SH", "IH", "T"],
        "",
        ["S", "T", "AA"],
        ["P", "AH"],
        "",
        ["B", "IY"],
        "",
        ["AH"],
        "",
        ["S", "M", "AA", "R", "T"],
        "",
        ["SH", "AA"],
        ["P", "AH"],
    ],
    [
        ["SH", "AA", "T"],
        "",
        ["AH"],
        "",
        ["K", "AA", "P"],
        "",
        ["D", "EY"],
        "",
        ["ER"],
        ["AW", "N", "D"],
        "",
        ["DH", "AH"],
        "",
        ["W", "EY"],
        "",
        ["B", "AW", "T"],
        "",
        ["T", "UW"],
        "",
        ["S", "T", "EY"],
    ],
    [
        ["B", "AH", "T"],
        "",
        ["HH", "UW", "D"],
        "",
        ["AH"],
        "",
        ["N", "OW"],
        "",
        ["DH", "EH", "R", "Z"],
        "",
        ["T", "UW"],
        "",
        ["M", "OW"],
        "",
        ["DH", "AE", "T"],
        "",
        ["W", "AH", "N"],
        ["D", "ER"],
        "",
        ["W", "EH", "R"],
        "",
        ["DH", "AH"],
        "",
        ["SH", "UW"],
        ["T", "ER"],
        "",
        ["G", "OW"],
    ],
    [
        ["B", "AW", "T"],
        "",
        ["T", "UW"],
        "",
        ["JH", "EH", "T"],
        "",
        ["G", "EH", "T"],
        "",
        ["HH", "IH", "M"],
        "",
        ["N", "AA", "T"],
        "",
        ["AH"],
        "",
        ["B", "EH", "T"],
        "",
        ["D", "EH", "D"],
        "",
        ["AH", "M"],
    ],
    [
        ["L", "EH", "T"],
        "",
        ["AH", "M"],
        "",
        ["S", "P", "IH", "T"],
        "",
        ["DH", "AH"],
        "",
        ["V", "EH"],
        ["N", "AH", "M"],
        "",
        ["S", "EH", "D"],
        "",
        ["AH", "M"],
        "",
        ["G", "AA", "T"],
        "",
        ["AH"],
        "",
        ["L", "AA", "T"],
        "",
        ["AH", "V"],
        "",
        ["SH", "IH", "T"],
        "",
        ["W", "IH", "DH"],
        "",
        ["AH", "M"],
    ],
    [
        ["L", "EH", "T"],
        "",
        ["DH", "AH"],
        "",
        ["R", "IH"],
        ["DH", "AH", "M"],
        "",
        ["HH", "IH", "T"],
        "",
        ["AH", "M"],
        "",
        ["IH", "T", "S"],
        "",
        ["S", "T", "R", "AO", "NG"],
        ["ER"],
        "",
        ["IH", "N"],
        "",
        ["DH", "AH"],
        "",
        ["AH"],
        ["DH", "ER"],
        "",
        ["V", "OY", "S"],
    ],
    [
        ["W", "IY"],
        "",
        ["M", "EY", "K", "S"],
        "",
        ["DH", "AH"],
        "",
        ["JH", "OY", "N", "T", "S"],
        "",
        ["DH", "AE", "T"],
        "",
        ["M", "EY", "K"],
        "",
        ["AH", "M"],
        "",
        ["S", "P", "R", "EH", "D"],
        "",
        ["AH", "M"],
        "",
        ["B", "UW"],
        ["T", "AH"],
        "",
        ["M", "OY", "S", "T"],
    ],
    [
        ["M", "AE", "N"],
        "",
        ["P", "L", "IY", "Z"],
        "",
        ["DH", "AH"],
        "",
        ["S", "T", "EY", "JH"],
        "",
        ["IH", "Z"],
        "",
        ["M", "EY", "D"],
        "",
        ["AH", "V"],
        "",
        ["P", "AE", "N"],
        ["T", "IY", "Z"],
    ],
    [
        ["F", "R", "AH", "M"],
        "",
        ["DH", "AH"],
        "",
        ["EY", "JH"],
        "",
        ["AH", "V"],
        "",
        ["B", "EY"],
        ["B", "IY"],
        "",
        ["HH", "UW"],
        ["CH", "IY", "Z"],
        "",
        ["AA", "N"],
        "",
        ["T", "UW"],
        "",
        ["DH", "AH"],
        "",
        ["G", "R", "AE"],
        ["N", "IY", "Z"],
    ],
    [
        ["B", "AE", "N"],
        "",
        ["M", "IY"],
        "",
        ["DH", "AH"],
        "",
        ["D", "OW"],
        "",
        ["R", "EY", "K"],
        "",
        ["D", "AE"],
        ["D", "IY"],
    ],
    [
        ["DH", "AH"],
        "",
        ["F", "L", "OW"],
        "",
        ["M", "EY", "K"],
        "",
        ["HH", "ER"],
        "",
        ["F", "AE"],
        ["T", "IY"],
        "",
        ["SH", "EY", "K"],
        "",
        ["P", "AE"],
        ["T", "IY"],
        "",
        ["K", "EY", "K"],
        "",
        ["P", "AE"],
        ["T", "IY"],
        "",
        ["K", "EY", "K"],
    ],
    [
        ["F", "AO", "R"],
        "",
        ["F", "EY", "K"],
        "",
        ["IH", "F"],
        "",
        ["HH", "IY"],
        "",
        ["W", "AA", "Z"],
        "",
        ["AH"],
        ["N", "IY"],
        ["T", "AH"],
        "",
        ["B", "EY"],
        ["K", "ER", "Z"],
        "",
        ["M", "AE", "N"],
    ],
    [
        ["HH", "IY", "D"],
        "",
        ["T", "EY", "K"],
        "",
        ["HH", "ER"],
        "",
        ["F", "AO", "R"],
        "",
        ["HH", "ER"],
        "",
        ["M", "AE"],
        ["S", "T", "ER", "Z"],
        "",
        ["HH", "IH", "T"],
        "",
        ["IH", "T"],
        "",
        ["W", "AH", "N", "S"],
        "",
        ["AE", "N"],
        "",
        ["SH", "EY", "K"],
        "",
        ["HH", "ER"],
        "",
        ["HH", "AE", "N", "D"],
    ],
    [
        ["AA", "N"],
        "",
        ["S", "AH", "M"],
        "",
        ["OW", "L"],
        "",
        ["TH", "AE", "NG", "K"],
        "",
        ["Y", "AA"],
        "",
        ["M", "AE", "M"],
        "",
        ["AE", "N"],
        "",
        ["G", "OW", "S", "T"],
        "",
        ["HH", "ER"],
    ],
    [
        ["SH", "IY"],
        "",
        ["K", "UH", "D"],
        "",
        ["M", "AY", "N", "D"],
        "",
        ["DH", "AH"],
        "",
        ["T", "OW"],
        ["S", "T", "ER"],
        "",
        ["IH", "F"],
        "",
        ["SH", "IY"],
        "",
        ["S", "AY", "N"],
        "",
        ["DH", "AH"],
        "",
        ["P", "OW"],
        ["S", "T", "ER"],
    ],
    [
        ["AH"],
        "",
        ["HH", "OW", "L"],
        "",
        ["HH", "OW", "S", "T"],
        "",
        ["AH", "V"],
        "",
        ["R", "OW"],
        ["L", "ER"],
        "",
        ["K", "OW"],
        ["S", "T", "ER"],
        "",
        ["R", "AY"],
        ["D", "ER", "Z"],
    ],
    [
        ["N", "AA", "T"],
        "",
        ["IH"],
        ["N", "AH", "F"],
        "",
        ["T", "R", "AE", "K", "S"],
        "",
        ["IH", "Z"],
        "",
        ["IH", "T"],
    ],
    [
        ["HH", "AA", "T"],
        "",
        ["IH"],
        ["N", "AH", "F"],
        "",
        ["B", "L", "AE", "K"],
        "",
        ["F", "AO", "R"],
        "",
        ["Y", "AA"],
    ],
    [
        ["IH", "T", "S"],
        "",
        ["T", "UW"],
        "",
        ["HH", "AA", "T"],
        "",
        ["T", "UW"],
        "",
        ["HH", "AE", "N"],
        ["D", "AH", "L"],
        "",
        ["Y", "UW"],
        "",
        ["G", "AA", "T"],
        "",
        ["B", "L", "UW"],
        "",
        ["S", "AE", "N"],
        ["D", "AH", "L", "Z"],
    ],
    [
        ["HH", "UW"],
        "",
        ["SH", "AA", "T"],
        "",
        ["Y", "AA"],
        "",
        ["UW"],
        "",
        ["G", "AA", "T"],
        "",
        ["Y", "UW"],
        "",
        ["N", "UW"],
        "",
        ["S", "P", "AA", "T", "S"],
        "",
        ["T", "UW"],
        "",
        ["V", "AE", "N"],
        ["D", "AH", "L"],
    ],
    [
        ["D", "UW"],
        "",
        ["N", "AA", "T"],
        "",
        ["S", "T", "AE", "N", "D"],
        "",
        ["S", "T", "IH", "L"],
        "",
        ["B", "OW", "S", "T"],
        "",
        ["Y", "OW"],
        "",
        ["S", "K", "IH", "L", "Z"],
    ],
    [
        ["K", "L", "OW", "S"],
        "",
        ["B", "AH", "T"],
        "",
        ["N", "OW"],
        "",
        ["K", "R", "IH", "L", "Z"],
        "",
        ["T", "OW", "S", "T"],
        "",
        ["F", "AO", "R"],
        "",
        ["P", "OW"],
        "",
        ["N", "IH", "L", "Z"],
        "",
        ["P", "OW", "S", "T"],
        "",
        ["N", "OW"],
        "",
        ["B", "IH", "L", "Z"],
    ],
    [
        ["K", "OW", "S", "T"],
        "",
        ["T", "UW"],
        "",
        ["K", "OW", "S", "T"],
        "",
        ["JH", "OW"],
        "",
        ["SH", "M", "OW", "Z"],
        "",
        ["F", "L", "OW", "Z"],
        "",
        ["IH", "L"],
        "",
        ["G", "OW"],
        "",
        ["CH", "IH", "L"],
    ],
    [
        ["N", "AA", "T"],
        "",
        ["S", "AH"],
        ["P", "OW", "Z", "D"],
        "",
        ["T", "UW"],
        "",
        ["OW"],
        ["V", "ER"],
        ["D", "OW", "S"],
        "",
        ["N", "OW"],
        "",
        ["D", "AA", "Z"],
        "",
        ["P", "IH", "L", "Z"],
    ],
    [
        ["AO", "F"],
        "",
        ["P", "R", "AY", "D"],
        "",
        ["T", "AY", "K", "S"],
        "",
        ["T", "AO", "K"],
        "",
        ["W", "AY", "D"],
        "",
        ["TH", "R", "UW"],
        "",
        ["S", "K", "AA", "R"],
        "",
        ["M", "IY", "T"],
    ],
    [
        ["AO", "F"],
        "",
        ["S", "AY", "D", "Z"],
        "",
        ["L", "AY", "K"],
        "",
        ["HH", "AW"],
        "",
        ["W", "ER", "F"],
        "",
        ["R", "AY", "D", "Z"],
        "",
        ["W", "IH", "DH"],
        "",
        ["S", "T", "AA", "R"],
        ["F", "IY", "T"],
    ],
    [
        ["T", "OW", "L", "D"],
        "",
        ["Y", "AA"],
        "",
        ["AA", "N"],
        "",
        ["S", "AH", "M"],
        "",
        ["G", "EH", "T"],
        "",
        ["R", "IH", "CH"],
        "",
        ["SH", "IH", "T"],
    ],
    [
        ["AE", "Z"],
        "",
        ["HH", "IY"],
        "",
        ["G", "EH", "T", "S"],
        "",
        ["OW", "L"],
        ["D", "ER"],
        "",
        ["HH", "IY"],
        "",
        ["G", "EH", "T", "S"],
        "",
        ["K", "OW", "L"],
        ["D", "ER"],
        "",
        ["DH", "AE", "N"],
        "",
        ["AH"],
        "",
        ["W", "IH", "CH"],
        "",
        ["T", "IH", "T"],
    ],
    [
        ["DH", "IH", "S"],
        "",
        ["IH", "Z"],
        "",
        ["IH", "T"],
        "",
        ["M", "EY", "K"],
        "",
        ["N", "OW"],
        "",
        ["M", "IH"],
        ["S", "T", "EY", "K", "S"],
    ],
    [["W", "EH", "R"], "", ["M", "AY"], "", ["N", "IH"], ["G", "AH"], "", ["G", "OW"]],
    [["F", "IH"], ["G", "ER"], ["OW"], "", ["F", "IH"], ["G", "ER"], ["OW"]],
    [
        ["OW", "Z"],
        "",
        ["B", "IY", "T", "S"],
        "",
        ["AH", "N", "D"],
        "",
        ["M", "AY"],
        "",
        ["R", "AY", "M", "Z"],
        "",
        ["AH"],
        ["T", "AE", "K"],
    ],
    [["AH"], "", ["S", "K", "EH"], ["R", "IY"], "", ["AE", "K", "T"]],
    [
        ["AO", "L"],
        "",
        ["B", "L", "AE", "K"],
        "",
        ["L", "AY", "K"],
        "",
        ["M", "IH", "Z"],
        "",
        ["M", "EH"],
        ["R", "IY"],
        "",
        ["M", "AE", "K"],
    ],
    [
        ["W", "EY", "T"],
        "",
        ["T", "IH", "L"],
        "",
        ["Y", "UW"],
        "",
        ["S", "IY"],
        "",
        ["AH", "M"],
        "",
        ["L", "AY", "V"],
        "",
        ["AA", "N"],
        "",
        ["DH", "AH"],
        "",
        ["P", "IY"],
        ["AE"],
        ["N", "OW"],
    ],
    [
        ["D", "UW", "M"],
        "",
        ["S", "IH", "NG", "Z"],
        "",
        ["S", "AH"],
        ["P", "R", "AA"],
        ["N", "OW"],
        "",
        ["L", "AY", "K"],
        "",
        ["UW"],
        ["N", "AH"],
        "",
        ["D", "W", "OW"],
        ["CH", "IY"],
        ["AA"],
        ["N", "OW"],
    ],
    [
        ["M", "AY"],
        "",
        ["M", "AA"],
        ["M", "AH"],
        "",
        ["T", "OW", "L", "D"],
        "",
        ["M", "IY"],
    ],
    [
        ["B", "L", "AE", "S", "T"],
        "",
        ["AH", "M"],
        "",
        ["AH", "N", "D"],
        "",
        ["P", "AE", "S"],
        "",
        ["HH", "ER"],
        "",
        ["HH", "ER"],
        "",
        ["G", "L", "AE", "S"],
        "",
        ["AH", "V"],
        "",
        ["OW", "L"],
        "",
        ["IY"],
    ],
    [
        ["N", "AA", "T"],
        "",
        ["T", "UW"],
        "",
        ["B", "IY"],
        "",
        ["T", "R", "AH"],
        ["B", "AH", "L"],
        ["S", "AH", "M"],
    ],
    [
        ["B", "AH", "T"],
        "",
        ["AY"],
        "",
        ["K", "UH", "D"],
        "",
        ["SH", "UH", "R"],
        "",
        ["Y", "UW", "S"],
        "",
        ["AH"],
        "",
        ["K", "W", "IH", "K"],
        "",
        ["SH", "AA", "T"],
        "",
        ["AH", "V"],
        "",
        ["D", "AH"],
        ["B", "AH", "L"],
        "",
        ["R", "AH", "M"],
    ],
    [
        ["N", "OW"],
        "",
        ["S", "T", "IH", "K"],
        "",
        ["AH", "V"],
        "",
        ["B", "AH"],
        ["B", "AH", "L"],
        "",
        ["G", "AH", "M"],
    ],
    [["AY"], "", ["L", "AY", "K"], "", ["AY", "S"], "", ["K", "R", "IY", "M"]],
    [
        ["W", "IY"],
        "",
        ["K", "UH", "D"],
        "",
        ["S", "K", "IH", "P"],
        "",
        ["DH", "AH"],
        "",
        ["W", "EH"],
        ["D", "IH", "N"],
    ],
    [["HH", "AE", "V"], "", ["AH"], "", ["N", "AY", "S"], "", ["D", "R", "IY", "M"]],
    [
        ["SH", "IY"],
        "",
        ["OW", "N"],
        ["L", "IY"],
        "",
        ["L", "EH", "T"],
        "",
        ["HH", "IH", "M"],
        "",
        ["S", "T", "IH", "K"],
        "",
        ["DH", "AH"],
        "",
        ["HH", "EH", "D"],
        "",
        ["IH", "N"],
    ],
    [],
]
figaro_text = [
    "[Produced by Madlib]\n",
    "\n",
    "[Verse: MF DOOM]\n",
    "The rest is empty with no brain, but the clever nerd\n",
    "The best emcee with no chain ya ever heard\n",
    "Take it from the TEC-9 holder\n",
    "They've bit but don't know their neck shine from Shinola\n",
    "Everything that glitters ain't fishscale\n",
    "Lemme think, don't let her faint get Ishmael\n",
    "A shot of Jack got her back it's not an act stack\n",
    "Forgot about the cackalack, holla back; clack-clack, blocka\n",
    "Villainy, feel him in ya heart chakra, chart-toppa\n",
    "Start-shit stoppa, be a smart shoppa\n",
    "Shot-a-Cop day around the way 'bout to stay\n",
    "But who'd a know there's two mo' that wonder where the shooter go\n",
    "'Bout to jet, get him, not a bet, dead 'em\n",
    "Let 'em spit the venom said 'em got a lot of shit with 'em\n",
    "Let the rhythm hit 'em, it's stronger in the other voice\n",
    "We makes the joints that make 'em spread 'em butta moist\n",
    "Man, please, the stage is made of panties\n",
    "From the age of baby hoochies on to the grannies\n",
    "Ban me the dough rake, daddy\n",
    "The flow make her fatty shake, patty cake, patty cake\n",
    "For fake, if he was Anita Baker's man\n",
    "He'd take her for her masters, hit it once an' shake her hand\n",
    "On some ol' thank ya ma'am an' ghost her\n",
    "She could mind the toaster if she sign the poster\n",
    "A whole host of roller coaster riders\n",
    "Not enough tracks (is it?)\n",
    "Hot enough black (for ya)\n",
    "It's too hot to handle, you got blue sandals\n",
    "Who shot ya? Ooh got you new spots to vandal?\n",
    "Do not stand still, boast yo' skills\n",
    "Close but no krills, toast for po' nils, post no bills\n",
    "Coast to coast Joe Shmoe's flows ill, go chill\n",
    "Not supposed to overdose No-Doz pills\n",
    "Off pride tykes talk wide through scar meat\n",
    "Off sides like how Worf rides with Starfleet\n",
    "Told ya, on some get-rich shit\n",
    "As he gets older he gets colder than a witch tit\n",
    "This is it, make no mistakes\n",
    "Where my nigga go?\n",
    "Figaro, Figaro\n",
    "O's beats and my rhymes attack\n",
    "A scary act\n",
    "All black like Ms. Mary Mack\n",
    "Wait 'til you see 'em live on the piano\n",
    'DOOM sings soprano, like, "Una, duociano"\n',
    "My momma told me\n",
    "Blast 'em and pass her her glass of Ol' E\n",
    "Not to be troublesome\n",
    "But I could sure use a quick shot of double rum\n",
    "No stick of bubble gum\n",
    "I like ice cream\n",
    "We could skip the weddin'\n",
    "Have a nice dream\n",
    "She only let him stick the head in\n",
    "\n",
]
